### ISSUE TITLE
Possible improvements and additions:

### ISSUE THREAD

**Issue by hebertcisco** [hebertcisco/pinsharest#7]
> ## Check with X to the solved problems.

- [X] Doesn’t is responsive to all devices.
- [X] Improve the design.
- [x] Adjust the colour palette for better visualization.
- [ ] If possible add an Iframe component instead of opening it in another tab.
- [ ] Add a button to upload an image and turn that image into Base64. Putting it in the image link field.

**Comment by tecnobert** [comment]
It is now responsive but still necessary to make adjustments.
